# -*- coding: utf-8 -*-
"""K-Means_BERTopic_Seeded.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T10jGVPu-7rgM92Gt2ee9UwPH1XvovnJ
"""

!pip install bertopic
!pip install gensim
from google.colab import drive
drive.mount('/content/drive')
import sys
from bertopic import BERTopic
from umap import UMAP
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans

# Commented out IPython magic to ensure Python compatibility.
# %run "/content/drive/MyDrive/Colab Notebooks/CombinedTrainingDataset.ipynb"
# %run "/content/drive/MyDrive/Colab Notebooks/StopWords.ipynb"

vectorizer_model = CountVectorizer(stop_words=my_stop_words, ngram_range=(1, 2), min_df=10, token_pattern=r'(?u)\b[a-zA-Z]{3,}\b')

seed_topic_list = [
    # 1. Inflation & Cost of Living
    ["inflation", "prices", "cost", "economy", "fed", "recession", "gas", "groceries",
    "purchasing", "power", "interest", "rates", "supply", "chain", "deficit",
    "spending", "cpi", "consumer", "index", "expensive", "affordability"],
    # 2. Taxes & Wealth Distribution
    ["tax", "taxes", "irs", "wealth", "billionaires", "loophole", "income", "corporate",
    "brackets", "capital", "gains", "revenue", "billionaire", "millionaires", "fair",
    "share", "audit", "deduction", "estates", "rich", "taxation"],
    # 3. Labor Rights & Unions
    ["labor", "unions", "strike", "workers", "wages", "minimum", "pay", "benefits",
    "bargaining", "unionization", "guild", "workplace", "employment", "overtime",
    "safety", "pension", "salaries", "staffing", "contract", "exploitation"],
    # 4. Housing & Real Estate
    ["housing", "rent", "mortgage", "zoning", "homelessness", "affordable", "eviction",
    "landlord", "tenants", "property", "real", "estate", "development", "market",
    "shortage", "equity", "gentrification", "shelter", "units", "inventory"],
    # 5. Student Debt & Education
    ["debt", "student", "loans", "forgiveness", "tuition", "college", "university",
    "degree", "graduates", "interest", "borrowers", "education", "academic",
    "scholarship", "fafsa", "repayment", "cancel", "default", "higher", "learning"],
    # 6. Healthcare & Insurance
    ["insurance", "healthcare", "medicare", "hospital", "coverage", "premiums", "prescription",
    "medicaid", "deductible", "copay", "provider", "doctor", "physician", "clinic", "treatment",
    "patient", "medical", "pharma", "aca", "obamacare"],
    # 7. Abortion & Reproductive Rights
    ["abortion", "roe", "wade", "planned", "parenthood", "fetus", "reproductive", "pregnancy",
    "choice", "prolife", "prochoice", "clinic", "viability", "contraception", "birth",
    "autonomy", "rights", "women", "dobbs", "legal"],
    # 8. Pandemic & Public Health
    ["covid", "pandemic", "vaccine", "mandate", "mask", "fauci", "virus", "health",
    "quarantine", "lockdown", "outbreak", "moderna", "pfizer", "booster", "cdc",
    "transmission", "distancing", "public", "emergency", "variants"],
    # 9. Drug Policy & Decriminalization
    ["drugs", "legalization", "marijuana", "weed", "decriminalization", "addiction", "overdose",
    "cannabis", "opioid", "fentanyl", "narcotics", "treatment", "dispensary", "rehab",
    "recreational", "controlled", "substances", "prison", "sentencing", "possession"],
    # 10. Gun Control & Second Amendment
    ["gun", "guns", "nra", "amendment", "firearm", "background", "checks", "shooting",
    "violence", "weapons", "rifle", "pistol", "ban", "arms", "safety",
    "massacre", "shooter", "regulation", "carry", "concealed"],
    # 11. LGBTQ+ & Gender Issues
    ["lgbtq", "trans", "transgender", "gay", "marriage", "gender", "rights", "pride",
    "queer", "homosexuality", "bisexual", "pronouns", "identity", "nonbinary", "transition",
    "equality", "discrimination", "hormone", "bathroom", "ban"],
    # 12. Racial Justice & Civil Rights
    ["race", "racism", "systemic", "blm", "black", "white", "diversity", "equity",
    "inclusion", "prejudice", "minority", "supremacy", "segregation", "reparations", "privilege",
    "civil", "rights", "marginalized", "profiling", "justice"],
    # 13. Policing & Law Enforcement
   ["police", "cops", "brutality", "reform", "defund", "officer", "arrest", "accountability",
    "sheriff", "patrol", "shooting", "force", "misconduct", "qualified", "immunity",
    "detective", "badge", "law", "enforcement", "swat"],
    # 14. Criminal Justice & Prison Reform
    ["prison", "justice", "criminal", "reform", "incarceration", "sentence", "inmates",
    "jail", "parole", "probation", "felony", "misdemeanor", "conviction", "recidivism", "rehab",
    "solitary", "warden", "exonerated", "private", "prisons"],
    # 15. Climate Change & Energy
    ["climate", "warming", "emissions", "carbon", "fossil", "green", "energy", "oil",
    "renewable", "solar", "wind", "methane", "epa", "environment", "pollution",
    "sustainability", "gas", "coal", "grid", "electric"],
    # 16. Infrastructure & Transportation
    ["infrastructure", "roads", "bridges", "transit", "rail", "amtrak", "grid", "transportation",
    "highway", "subway", "trains", "tunnel", "construction", "pipes", "broadband",
    "water", "sewage", "logistics", "electric", "vehicles"],
    # 17. Voting Rights & Elections
    ["voting", "voters", "election", "fraud", "ballot", "gerrymandering", "suppression",
    "electoral", "college", "registration", "absentee", "primary", "midterms", "polling", "census",
    "districts", "integrity", "disenfranchisement", "turnout", "early"],
    # 18. Supreme Court & Judiciary
    ["supreme", "court", "scotus", "justices", "judge", "ruling", "bench", "nominee",
    "jurisdiction", "unconstitutional", "precedent", "confirmation", "docket", "circuit", "legal",
    "opinion", "constitution", "judicial", "overturn", "appeal"],
    # 19. Campaign Finance & Corruption
    ["campaign", "finance", "citizens", "united", "pac", "lobbying", "donors", "corruption",
    "superpac", "bribery", "ethics", "lobbyist", "funding", "special", "interests",
    "dark", "money", "disclosure", "clout", "quid"],
    # 20. Executive Power & Investigations
    ["impeachment", "subpoena", "treason", "investigation", "committee", "hearing", "testimony",
    "executive", "privilege", "pardon", "cabinet", "veto", "prosecutor", "contempt", "oversight",
    "scandal", "witness", "perjury", "doj", "order"],
    # 21. Immigration & Border Security
   ["border", "immigration", "immigrants", "wall", "asylum", "ice", "deportation", "migrants",
    "citizenship", "visa", "illegal", "legal", "daca", "patrol", "crossing",
    "refugee", "customs", "undocumented", "naturalization", "h1b"],
    # 22. Russia & Ukraine Conflict
    ["ukraine", "russia", "putin", "zelensky", "nato", "war", "sanctions", "invasion",
    "kremlin", "kyiv", "moscow", "missiles", "intelligence", "offensive", "tanks",
    "aid", "weapons", "ceasefire", "territory", "victory"],
    # 23. China & Global Trade
    ["china", "taiwan", "tariffs", "ccp", "trade", "beijing", "espionage", "manufacturing",
    "semiconductors", "supply", "chain", "exports", "imports", "economy", "sanctions",
    "tensions", "dominance", "competition", "shipping", "xi"],
    # 24. Middle East Relations
    ["israel", "palestine", "gaza", "hamas", "middle", "east", "jewish", "antisemitism",
    "conflict", "iran", "jerusalem", "tel", "aviv", "settlements", "apartheid",
    "hezbollah", "oil", "syria", "treaty", "hostages"],
    # 25. Big Tech, Privacy & Social Media
    ["tech", "privacy", "tiktok", "facebook", "censorship", "algorithm", "data", "monopoly",
    "silicon", "valley", "encryption", "surveillance", "platform", "twitter", "google",
    "antitrust", "regulation", "section", "230", "internet"]
]

docs = combined_data['Combined_Content'].tolist()

umap_model = UMAP( n_neighbors=15, n_components=5, min_dist=0.0,metric='cosine',random_state=42)

cluster_model = KMeans(n_clusters=49, random_state=42)

topic_model = BERTopic(hdbscan_model=cluster_model,umap_model=umap_model,vectorizer_model=vectorizer_model,seed_topic_list=seed_topic_list,calculate_probabilities=True,verbose=True)
topics, probs = topic_model.fit_transform(docs)
freq = topic_model.get_topic_info()

topic_info = topic_model.get_topic_info()
formatted_labels = []

for index, row in topic_info.iterrows():
    topic_id = row['Topic']
    words = row['Representation']

    if topic_id == -1:
        clean_label = "Other / Irrelevant / Noise"
    else:
        clean_label = ", ".join(words)
    formatted_labels.append(clean_label)
for i, label in enumerate(formatted_labels):
    print(f"Index {i}: {label}")

llm_topic_list = formatted_labels

info = topic_model.get_topic_info()
print(info)

topics_to_merge = [
    [38, 43, 44, 46, 47 48],
    [6,7,13],
    [8, 16],
    [25, 42, 42, 45]
]
topic_model.merge_topics(docs, topics_to_merge)

formatted_labels = []

for topic_id in topic_model.get_topics():

    words_with_scores = topic_model.get_topic(topic_id)
    words_only = [word for word, score in words_with_scores[:20]]
    if topic_id == -1:
        clean_label = "Other / Irrelevant / Noise"
    else:
        clean_label = ", ".join(words_only)
    formatted_labels.append(clean_label)
for i, label in enumerate(formatted_labels):
    print(f"Index {i}: {label}")

topic_mapping = {
    0: "INVESTIGATION: Government Investigations",
    1: "ELECTIONS: Campaigns & Primaries",
    2: "MODERATION: Community Interaction Messages",
    3: "POLITICS: Legislative Branch & Governance",
    4: "IDEOLOGY: Economic & Political Systems",
    5: "POLITICS: Ethical Misconduct & Accountability",
    6: "FOREIGN POLICY: Russia-Ukraine Conflict",
    7: "CULTURE: Values & Historical Identity",
    8: "IDEOLOGY: Extremism & Global Conflict",
    9: "LABOR: Workers Rights & Unions",
    10: "SOCIAL: Race & Civil Rights",
    11: "ECONOMY: Economics & Markets",
    12: "SOCIAL: Gender & Identity",
    13: "MEDIA: News Outlets & Propaganda",
    14: "ENVIRONMENT & IMMIGRATION: Climate & Borders",
    15: "POLITICS: Impeachment & Presidential Trials",
    16: "TECH: Social Media & Platform Rules",
    17: "ECONOMY: Wealth & Taxation",
    18: "POLITICS: Campaign Finance & Corruption",
    19: "HEALTH: Healthcare Policy & Insurance",
    20: "SOCIAL: Reproductive Rights & Abortion",
    21: "FOREIGN POLICY: Latin America & Global Policy",
    22: "POLICY: Violations & Bans",
    23: "HEALTH: COVID-19 & Public Health",
    24: "JUSTICE: Criminal Justice & Incarceration",
    25: "JUSTICE: Gun Control & 2nd Amendment",
    26: "JUSTICE: Policing & Law Enforcement",
    27: "JUSTICE: Supreme Court & Legal Rulings",
    28: "ECONOMY: Housing & Real Estate",
    29: "POLITICS: State Governance & Education",
    30: "SOCIAL: Student Debt & Higher Education",
    31: "JUSTICE: Drug Policy & Legalization",
    32: "NOISE: General Conversational Filler"
}

import pickle
save_path = '/content/drive/MyDrive/K-means_bertopic_model_data.pkl'
import pickle
with open(save_path, 'wb') as f:
    pickle.dump({
        'vectorizer': vectorizer_model,
        'topic_model': topic_model,
        'human_labels': topic_mapping
    }, f)

print("BERTopic model and labels saved as 'K-means_bertopic_model_data.pkl'")