# -*- coding: utf-8 -*-
"""CombinedTrainingDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LpB7ujYxcO52GUq9PaYeVT3BEtHq6fv
"""

import os
import pandas as pd
import kagglehub

path_for_lib_cons = kagglehub.dataset_download("neelgajare/liberals-vs-conservatives-on-reddit-13000-posts")
csv_file_1 = None

for filename in os.listdir(path_for_lib_cons):
    if filename.endswith(".csv"):
        csv_file_1 = os.path.join(path_for_lib_cons, filename)
        break

if csv_file_1:
    cons_vs_lib = pd.read_csv(csv_file_1)
    cons_vs_lib['Title'] = cons_vs_lib['Title'].fillna('')
    cons_vs_lib['Text'] = cons_vs_lib['Text'].fillna('')
    cons_vs_lib['Combined_Content'] = cons_vs_lib['Title'] + " " + cons_vs_lib['Text']
    cons_vs_lib['Source_Dataset'] = 'Liberals_vs_Conservatives'

path_for_politics_sub = kagglehub.dataset_download("smagnan/1-million-reddit-comments-from-40-subreddits")
csv_file_2 = None

for filename in os.listdir(path_for_politics_sub):
    if filename.endswith(".csv"):
        csv_file_2 = os.path.join(path_for_politics_sub, filename)
        break

if csv_file_2:
    politicsdf = pd.read_csv(csv_file_2)
    politics_sub = politicsdf[politicsdf['subreddit'] == 'politics'].copy()
    politics_sub = politics_sub.rename(columns={'body': 'Combined_Content'})
    politics_sub['Source_Dataset'] = '1M_Comments_Politics'

if not cons_vs_lib.empty and not politics_sub.empty:
    combined_data = pd.concat([cons_vs_lib, politics_sub], ignore_index=True)
