# -*- coding: utf-8 -*-
"""TFIDFBaselineTopicModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8f_ARLDJ17ZkX9Mx1ui6rq-C7rjNVeg
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from google.colab import drive
drive.mount('/content/drive')
import pickle

# Commented out IPython magic to ensure Python compatibility.
# %run "/content/drive/MyDrive/Colab Notebooks/CombinedTrainingDataset.ipynb"
# %run "/content/drive/MyDrive/Colab Notebooks/StopWords.ipynb"

docs = combined_data['Combined_Content'].tolist()

tfidf_vectorizer = TfidfVectorizer(stop_words=my_stop_words, min_df=20, token_pattern=r'(?u)\b[a-zA-Z]{3,}\b')

tfidf_matrix = tfidf_vectorizer.fit_transform(docs)
num_topics = 50
nmf_model = NMF( n_components=num_topics, random_state=42, init='nndsvda', max_iter=500 )
nmf_W = nmf_model.fit_transform(tfidf_matrix)
nmf_H = nmf_model.components_

tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
n_top_words = 20

tfidf_formatted_labels = []
for topic_idx, topic in enumerate(nmf_H):
    top_features_ind = topic.argsort()[:-n_top_words - 1:-1]
    top_features = [tfidf_feature_names[i] for i in top_features_ind]
    clean_label = ", ".join(top_features)
    tfidf_formatted_labels.append(clean_label)

print("\n--- TF-IDF Baseline Topics ---")
for i, label in enumerate(tfidf_formatted_labels):
    print(f"Topic {i}: {label}")

baseline_topic_list = tfidf_formatted_labels

topic_id_to_label = {
    0: "Noise/Filler",
    1: "Mueller Investigation Findings",
    2: "URLs & Web Metadata",
    3: "Bill Barr Perjury Allegations",
    4: "Life & Big Questions",
    5: "Senate Hearing Debates",
    6: "Mueller Report Release & Redactions",
    7: "Russia-Ukraine Invasion & NATO",
    8: "Special Counsel Public Context",
    9: "House Oversight & Subpoenas",
    10: "Fighting for Accountability",
    11: "Fox, CNN & Media Bias",
    12: "Congress vs. The Law",
    13: "Political Talking Points & Emails",
    14: "How Politics Works",
    15: "Capitalism vs. Socialism Debate",
    16: "Reddit Community Feedback",
    17: "NY Politics & Green New Deal",
    18: "Senate Majority & McConnell",
    19: "Identity Politics & Extremism",
    20: "Leaked Letters & Documents",
    21: "Arguing over Definitions",
    22: "Socialism & Welfare",
    23: "War & Anti-War Views",
    24: "DOJ Charges & Statements",
    25: "Impeachment Trial",
    26: "Health Care & Insurance",
    27: "Campaign Finance & Economic Costs",
    28: "Primary Elections & Voter Base",
    29: "Jobs & Fair Pay",
    30: "Power & Influences",
    31: "Russia Sanctions & Collusion",
    32: "Political Skepticism",
    33: "Strong Public Reactions",
    34: "Critique of News Coverage",
    35: "Supreme Court & Judges",
    36: "Barr's Report Summary",
    37: "Race & Civil Rights History",
    38: "Approval Ratings & Polls",
    39: "Progressive & Socialist Sentiment",
    40: "Rating the Attorney General",
    41: "Taxes & The Wealthy",
    42: "Violence & Extremism",
    43: "Law Enforcement & Abortion Rights",
    44: "Calls for Resignation & Action",
    45: "Legal Rights & Lying",
    46: "Unions & Strikes",
    47: "Obstruction & Collusion",
    48: "Lying Under Oath",
    49: "China & Communism"
}

dominant_topics = nmf_W.argmax(axis=1)
results_df = pd.DataFrame({
    'Document_Content': docs,
    'Topic_ID': dominant_topics
})

results_df['Topic_Label'] = results_df['Topic_ID'].map(topic_id_to_label)
print(results_df[['Document_Content', 'Topic_Label']])

save_path = '/content/drive/MyDrive/tfidf_topic_model.pkl'
with open(save_path, 'wb') as f:
    pickle.dump({
        'vectorizer': tfidf_vectorizer,
        'nmf_model': nmf_model,
        'top_words_labels': tfidf_formatted_labels,
        'human_labels': topic_id_to_label
    }, f)
print("topic model saved as 'tfidf_topic_model.pkl'")